server:
  port: 7001
  tomcat:    uri-encoding: UTF-8
spring:  http:    encoding:      force: true
      charset: UTF-8
      enabled: true
  freemarker:    template-loader-path: classpath:/templates    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    suffix: .html
