server:
  port: 8001
  
spring:
  application:
    name: lzy-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lzysdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true
    
mybatis:
  mapper-locations:  - mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:  level:    com.pro.msv.server.mapper: debug